# Generated by Django 3.2.9 on 2023-03-03 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom', '0002_anofiscal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funsionariu', '0002_auto_20230301_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefisiariuUKL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran', models.CharField(max_length=200, null=True)),
                ('seksu', models.CharField(blank=True, choices=[('Mane', 'Mane'), ('Feto', 'Feto')], max_length=10, null=True)),
                ('nu_telefone', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Benefisiariu_Image', verbose_name='Upload Imajen Survey')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('administrativepost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefitAdministrativePost', to='custom.administrativepost')),
                ('aldeia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.aldeia')),
                ('municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefitMunicipality', to='custom.municipality')),
            ],
        ),
        migrations.CreateModel(
            name='ImplementasaunUKL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(null=True)),
                ('enddate', models.DateField(null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Orsamentu Projetu')),
                ('distancemun', models.CharField(blank=True, max_length=200, null=True)),
                ('implementby', models.CharField(blank=True, max_length=200, null=True)),
                ('statusImplementasaun', models.CharField(blank=True, choices=[('Not Start', 'Not Start'), ('On Going', 'On Going'), ('Pending', 'Pending'), ('Abandone', 'Abandone'), ('Complate', 'Complate')], default='Not Start', max_length=30, null=True)),
                ('is_locked', models.BooleanField(blank=True, default=False, null=True)),
                ('is_sent', models.BooleanField(blank=True, default=False, null=True)),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('is_rejected', models.BooleanField(blank=True, default=False, null=True)),
                ('rejected_info', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('administrativepost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.administrativepost')),
                ('aldeia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.aldeia')),
                ('benefisiariu', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='implementationbenefit', to='ukl.benefisiariuukl')),
                ('municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.municipality')),
            ],
        ),
        migrations.CreateModel(
            name='ImplementationMonitoringUKL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pursentu_programa', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Pursentu Implementasaun')),
                ('pursentu_acumulativa', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Pursentu Acumulativa')),
                ('orsamentu_gastu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Orsamentu Gastus')),
                ('orsamentu_acumulativa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Orsamentu Acumulativa')),
                ('komentariu', models.TextField(blank=True, null=True)),
                ('monitoring_date', models.DateField()),
                ('is_locked', models.BooleanField(blank=True, default=False, null=True)),
                ('is_sent', models.BooleanField(blank=True, default=False, null=True)),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('is_rejected', models.BooleanField(blank=True, default=False, null=True)),
                ('rejected_info', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('funsionariu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funsionariu.funsionariu')),
                ('implementasaun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='implementasaun', to='ukl.implementasaunukl')),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyUKL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aldeia', models.CharField(blank=True, max_length=222, null=True, verbose_name="Survey iha Aldeia ka bairu ne'ebe?")),
                ('surveyDate', models.DateField(null=True, verbose_name='Data Survey')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Informasaun Adisional')),
                ('is_locked', models.BooleanField(blank=True, default=False, null=True)),
                ('is_sent', models.BooleanField(blank=True, default=False, null=True)),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('is_rejected', models.BooleanField(blank=True, default=False, null=True)),
                ('is_implemented', models.BooleanField(blank=True, default=False, null=True)),
                ('rejected_info', models.TextField(blank=True, null=True)),
                ('administrativepost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.administrativepost', verbose_name="Survey iha Postu ne'ebe?")),
                ('municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.municipality', verbose_name="Survey iha Munisipiu ne'ebe?")),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.village', verbose_name="Survey iha Suku ne'ebe?")),
            ],
        ),
        migrations.CreateModel(
            name='SurveyUKLImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Survey_UKL_Image', verbose_name='Upload Imajen Survey')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ukl.surveyukl', verbose_name='Dadus Survey')),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImplementationMonitoringUKLImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ImplementationMonitoringUKL', verbose_name='Upload Imajen Monitoring Implementasaun')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('monitoring', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ukl.implementationmonitoringukl', verbose_name='Dadus Monitoring Implementasaun UKL')),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImplementasaunUKLImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ImplementasaunUKL', verbose_name='Upload Imajen Implementasaun')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('implementasaun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ukl.implementasaunukl', verbose_name='Dadus Implementasaun UKL')),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='implementasaunukl',
            name='survey',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implementationsurvey', to='ukl.surveyukl'),
        ),
        migrations.AddField(
            model_name='implementasaunukl',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='implementasaunukl',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.village'),
        ),
        migrations.AddField(
            model_name='implementasaunukl',
            name='year',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implementationyear', to='custom.anofiscal'),
        ),
        migrations.CreateModel(
            name='ImplementasaunPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='implementationLocation')),
                ('implementasaun', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='implementationLocation', to='ukl.implementasaunukl')),
            ],
        ),
        migrations.AddField(
            model_name='benefisiariuukl',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ukl.surveyukl', verbose_name='Dadus Survey'),
        ),
        migrations.AddField(
            model_name='benefisiariuukl',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='benefisiariuukl',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefitVillage', to='custom.village'),
        ),
    ]
