# Generated by Django 3.2.9 on 2023-03-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukl', '0004_benefisiariudoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefisiariuukl',
            name='eleitoral',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Nu. Kartaun Eleitoral'),
        ),
    ]
