# Generated by Django 3.2.9 on 2023-03-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukl', '0005_benefisiariuukl_eleitoral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefisiariuukl',
            name='eleitoral',
            field=models.IntegerField(null=True, unique=True, verbose_name='Nu. Kartaun Eleitoral'),
        ),
    ]
