# Generated by Django 3.2.9 on 2023-03-04 03:08

import custom.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukl', '0007_benefisiariudoc_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefisiariudoc',
            name='file',
        ),
        migrations.AddField(
            model_name='benefisiariudoc',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=custom.utils.upload_doc_benefit, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])], verbose_name='Upload Dokumentu'),
        ),
    ]
