# Generated by Django 3.2.9 on 2023-03-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_anofiscal'),
        ('ukl', '0008_auto_20230304_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementasaunukl',
            name='medida',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Medida Uma'),
        ),
        migrations.AlterField(
            model_name='implementasaunukl',
            name='distancemun',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Distansia husi Munisipiu'),
        ),
        migrations.AlterField(
            model_name='implementasaunukl',
            name='implementby',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Implementa husi'),
        ),
        migrations.AlterField(
            model_name='implementasaunukl',
            name='statusImplementasaun',
            field=models.CharField(blank=True, choices=[('Not Start', 'Not Start'), ('On Going', 'On Going'), ('Pending', 'Pending'), ('Abandone', 'Abandone'), ('Complate', 'Complate')], default='Not Start', max_length=30, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='implementasaunukl',
            name='year',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implementationyear', to='custom.anofiscal', verbose_name='Ano Fiskal'),
        ),
    ]
