# Generated by Django 3.2.9 on 2023-03-06 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_anofiscal'),
        ('ukl', '0009_auto_20230304_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefisiariuukl',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Benefisiariu_Image', verbose_name='Upload Fotografia Benefisiariu (Ex: .PNG or JPG)'),
        ),
        migrations.AlterField(
            model_name='implementasaunukl',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implementationyear', to='custom.anofiscal', verbose_name='Ano Fiskal'),
        ),
    ]
