# Generated by Django 3.2.9 on 2023-03-06 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ukl', '0010_auto_20230306_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementasaunukl',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implementationsurvey', to='ukl.surveyukl'),
        ),
    ]
