# Generated by Django 3.2.9 on 2023-03-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukl', '0011_alter_implementasaunukl_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementasaunuklimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Implementasaun_UKL', verbose_name='Upload Imajen Implementasaun'),
        ),
    ]
