# Generated by Django 3.2.9 on 2023-03-13 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ukl', '0012_alter_implementasaunuklimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implementasaunpoint',
            name='implementasaun',
        ),
        migrations.AddField(
            model_name='implementasaunpoint',
            name='survey',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveyLocation', to='ukl.surveyukl'),
        ),
    ]
