# Generated by Django 3.2.9 on 2023-03-01 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
        ('funsionariu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funsionariu',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='funsionariu',
            name='is_mun',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='funsionariu',
            name='is_nac',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='funsionariu',
            name='is_post',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='funsionariu',
            name='areaadministrativepost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AreaAdministrativePost', to='custom.administrativepost', verbose_name='Area Servisu (Postu)'),
        ),
        migrations.AlterField(
            model_name='funsionariu',
            name='areamunicipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AreaMunicipality', to='custom.municipality', verbose_name='Area Servisu (Munisipiu)'),
        ),
        migrations.AlterField(
            model_name='funsionariu',
            name='areavillage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AreaVillage', to='custom.village', verbose_name='Area Servisu (Suku)'),
        ),
        migrations.AlterField(
            model_name='funsionariu',
            name='tipu_f',
            field=models.CharField(blank=True, choices=[('Diretor Nacional', 'Diretor Nacional'), ('Diretor Municipio', 'Diretor Municipio'), ('Funcionario Posto', 'Funcionario Posto'), ('Funcionario EIP', 'Funcionario EIP')], max_length=30, null=True),
        ),
    ]
