# Generated by Django 3.2.9 on 2023-03-06 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsionariu', '0002_auto_20230301_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfunsionariu',
            name='funsionariu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userFunsionariu', to='funsionariu.funsionariu'),
        ),
    ]
