# Generated by Django 3.2.9 on 2023-03-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50, verbose_name='Ano Fiskal')),
            ],
            options={
                'verbose_name_plural': 'Dadus Custom Ba AnoFiscal',
            },
        ),
    ]
